### ISSUE TITLE
path not specified

### ISSUE THREAD

**Issue by Dunebook** [Classy-Geeks/laravel-potion#13]
whenever i am making command php artisan potion:make-assets 
its saying the system canot find the path specified........ may be more docmentation is needed

**Comment by mattglover11** [comment]
If you pull my fork of this project, you can use --debug to show you all the paths and files it attempts to make so you can work out what is failing.

**Comment by mattglover11** [comment]
Laravel 5.1 only

**Comment by mattglover11** [comment]
https://github.com/sparkeleven/laravel-potion

**Comment by Dunebook** [comment]
i am using latest version of laravel

**Comment by Dunebook** [comment]
my css and js files are present in resources/assets folder when ever i am running this command php artisan potion:make-assets its saying system cant find the path specified .... please tell am i doing something wrong or i have to add something more in command

**Comment by mattrmiller** [comment]
I have plans to add better output, so that you can see what might be going wrong. I will try to find some time today or tonight to get this into the main branch.

**Comment by mattrmiller** [comment]
I just pushed v1.0.3 which adds more output.
It will output what directory it's trying to create, but more importantly it will output what it is pulling from your config for assets and resource paths.

Just a reminder:
assets: is the folder that will be used to store final assets that are created by potion.
resources: are files/folders that are used to create the final assets.

Thank you for your contribution and let me know if you have further issues.

**Comment by Dunebook** [comment]
ok let me try it
