### ISSUE TITLE
do you have specific example 

### ISSUE THREAD

**Issue by wasiqaftab** [Classy-Geeks/laravel-potion#14]
HI

do you have any specific example if i need to use scss how i can use this package

**Comment by mattrmiller** [comment]
I do not, but the format is the exact same as the sample config in there. Just add your files, and filter and it will process SCSS files.

**Comment by mattglover11** [comment]
Wasi - here are some excerpts from mine....

```
            'resources' => [
            'styles/scss/main.scss',


            'output' => 'app.css'
```

As Matt said it is no different. In my case, main.scss is my central include file for all my other scss files like variables, modules, includes, mixin's etc.

I do a lot of Sass/Compass front end work, so I have a fork of Matt's excellent repo you might like at https://github.com/mattyglover/laravel-potion

Specifically it allows for output path modifiers within potions which can be handy :D

**Comment by mattglover11** [comment]
I should say though that the example I included above works out of the box with this repo..

**Comment by wasiqaftab** [comment]
@mattyglover thanks alot it works for me :)
