### ISSUE TITLE
SCSSPHP locked to v0.1.1, latest is 0.6.6

### ISSUE THREAD

**Issue by almightynassar** [Classy-Geeks/laravel-potion#16]
Is there a reason why leafo/scssphp is locked to v0.1.1? I require some newer functionality available in the later versions.

Requiring a newer version of leafo/scss in my composer.json will revert potion to an earlier version (v.1.0.0) instead of v1.0.3 (obviously because that version of potion only suggests scssphp instead of requiring it).

I could do a PR, but I wanted to make sure that there wasn't some sort of underlying issue where we are required to use scssphp v0.1.1 instead of something more up-to-date.

**Comment by almightynassar** [comment]
Partially resolved by updating the composer.json to use dev-master instead of the tags. I say partially because obviously it would be better to use release versions instead of the development branch.

**Comment by mattrmiller** [comment]
@almightynassar Honestly, I just haven't had time to keep up with the various libraries. If you update it, test it, and put in a pull request I will merge it in.

Thanks.
