### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by maxi032** [Classy-Geeks/laravel-potion#5]
When I do composer update I get a dependency error:
  Problem 1
    - Installation request for classygeeks/potion 1.0._@dev -> satisfiable by cl
assygeeks/potion[1.0.x-dev].
    - classygeeks/potion 1.0.x-dev requires kriswallsmith/assetic 1.3._@dev -> n
o matching package found.

Potential causes:
- A typo in the package name
- The package is not available in a stable-enough version according to your min
  imum-stability setting
  see https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion f
  or more details.

Read http://getcomposer.org/doc/articles/troubleshooting.md for further common
 problems.

**Comment by mattrmiller** [comment]
I do not know why some people are getting this error. No matter what I do I can not replicate it, as that version of assetic is very much valid: https://packagist.org/packages/kriswallsmith/assetic

Can you please post your composer.json file and let me know what you are running exactly?

**Comment by maxi032** [comment]
Thank you for your reply. I've done some more tests and I managed to install it only after I installed each one of your dependency packages in my composer.json

**Comment by mattrmiller** [comment]
Can you let me know which dependency so I can update Potion composer file.

**Comment by maxi032** [comment]
All of your dependencies listed on the packagist page: https://packagist.org/packages/classygeeks/potion 

So I first installed "kriswallsmith/assetic": "1.3.*@dev" and then it crushed with the next package from the list, I installed that package also and so on. The thing is that it is not the correct behavior.

Also, Now that I installed it how do I use it?

**Comment by mattrmiller** [comment]
I understand this is not the correct behavior. I am trying to figure out why listing assetic as a requirement in my composer file breaks install for some people.

I have never been able to replicate this. Are you running a composer install or composer update?

As per how to use it once installed, please see the main repository page for instructions.

**Comment by maxi032** [comment]
I was doing composer update

**Comment by maxi032** [comment]
the problem was not just with the assetic. After I installed assetic, it broke on the next packages

**Comment by mattrmiller** [comment]
I just did a clean laravel 5 install:

Added "classygeeks/potion": "1.1.*@dev" to my composer file

Rand composer update

All is fine.

I am not sure what is going on here for certain installs. Hard to say without seeing what their composer.json file looks like.

**Comment by tudor2004** [comment]
The issue is still there. Made a fresh laravel 5 install added "classygeeks/potion": "1.1.*@dev" but following error appears 

```
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for classygeeks/potion 1.1.*@dev -> satisfiable by classygeeks/potion[1.1.x-dev].
    - classygeeks/potion 1.1.x-dev requires kriswallsmith/assetic 1.3.*@dev -> no matching package found.

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion> for more details.

Read <http://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.
```

Here is my composer.json file 

```
{
    "name": "laravel/laravel",
    "description": "The Laravel Framework.",
    "keywords": ["framework", "laravel"],
    "license": "MIT",
    "type": "project",
    "require": {
        "laravel/framework": "5.0.*",
        "classygeeks/potion": "1.1.*@dev"

    },
    "require-dev": {
        "phpunit/phpunit": "~4.0",
        "phpspec/phpspec": "~2.1"
    },
    "autoload": {
        "classmap": [
            "database"
        ],
        "psr-4": {
            "App\\": "app/"
        }
    },
    "autoload-dev": {
        "classmap": [
            "tests/TestCase.php"
        ]
    },
    "scripts": {
        "post-install-cmd": [
            "php artisan clear-compiled",
            "php artisan optimize"
        ],
        "pre-update-cmd": [
                "php artisan clear-compiled"
            ],
        "post-update-cmd": [
            "php artisan optimize"
        ],
        "post-create-project-cmd": [
            "php -r \"copy('.env.example', '.env');\"",
            "php artisan key:generate"
        ]
    },
    "config": {
        "minimum-stability": "dev",
        "preferred-install": "dist"
    }
}
```

**Comment by mattrmiller** [comment]
Do not use dev versions, they are rarely stable when it comes to composer packages.

"classygeeks/potion": "1.0.*"

Make sure you clear composers cache before doing another update.

As of today I have moved all "filters" to suggested packages and put them on the user to determine which ones they use and what versions they wish to use. It is causing too much support and install problems.
