### ISSUE TITLE
Undefined index: assets_path in L5

### ISSUE THREAD

**Issue by tudor2004** [Classy-Geeks/laravel-potion#7]
Running php artisan potion:make-assets in Laravel 5 throws "Undefined index: assets_path" exception. As far as I see there is a problem in the PotionServiceProvider getConfig() method. Replacing  

```
\Config::get("potion{$this->packageSeparator}config");
```

with 

```
\Config::get("potion");
```

seems to fix the issue

**Comment by mattrmiller** [comment]
Thank you. I will address this.
